[package]
name = "api"
version = "0.1.0"
edition = "2021"

[workspace]
members = ['.', 'entity', 'migration']

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }
axum = { version = "0.5.16", features = ["headers"] }
dotenvy = "0.15.3"
headers = "0.3.8"
jsonwebtoken = "8.1.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1.21.1", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }

[dependencies.sea-orm]
version = "0.9.2"
features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]
